project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!files/"
  resources:
    - "*.json"
    - "files"
    - "_extensions"

execute:
  freeze: auto


website:
  repo-url: https://github.com/inqs909/m2012_f25
  title: "MATH 201"
  site-url: www.inqs.info/m2012_f25
  navbar:
    right:
      - syllabus_201.qmd
      - syllabus_202.qmd
      - lectures.qmd
      - ec.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



